# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SecureAplus
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
LIBS += -L"WS2_32.lib"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(SecureAplus.pri)
win32:RC_FILE = SecureAplus.rc
QT += declarative