#pragma once

enum {CMD_LINE_RULE_EXACT_MATCH, CMD_LINE_RULE_START_WITH, CMD_LINE_RULE_CONTAINS};
enum {CMD_LINE_CASE_SENSITIVE, CMD_LINE_CASE_INSENSITIVE};
enum {CMD_LINE_ACTION_NONE, CMD_LINE_ACTION_BLOCK, CMD_ACTION_LET_USER_DECIDE, CMD_ACTION_NEVER_TRUST_PERMANENTLY};
